### ISSUE TITLE
can't run Gradualizer

### ISSUE THREAD

**Issue by tim2CF** [josefs/Gradualizer#4] opened 2018-06-04 14:35 UTC
Something is wrong with Erlang version?
Trying it with OTP20 / macos

```
Iljas-iMac:Gradualizer timcf$ make
erlc absform.erl
erlc constraints.erl
erlc gradualizer_db.erl
erlc typechecker.erl
typechecker.erl:5: Warning: export_all flag enabled - all functions will be exported
erlc typelib.erl
erl *.beam
2018-06-04 17:27:51 application_controller: ~ts: ~ts~n
	["syntax error before: ","'.'"]
	"absform.beam"
{"could not start kernel pid",application_controller,"{bad_environment_value,\"absform.beam\"}"}
could not start kernel pid (application_controller) ({bad_environment_value,"absform.beam"})

Crash dump is being written to: erl_crash.dump...done
make: *** [run] Error 1
```

**Comment by josefs** [comment] 2018-06-04 19:38
I'm afraid I have no idea what's going on here. 
Perhaps you can try to just start the erlang shell and compile the modules by hand. I.e.

```erlang
1> c(absform).
{ok,absform}
2> c(constraints).
{ok,constraints}
3> c(gradualizer_db).
{ok,gradualizer_db}
4> c(typechecker).
typechecker.erl:5: Warning: export_all flag enabled - all functions will be exported
{ok,typechecker}
5> c(typelib).
{ok,typelib}
6> typechecker:type_check_file("tests/append.erl").
ok
7> 
```

**Comment by tim2CF** [comment] 2018-06-05 07:56
yes, it works, thanks!

**Comment by josefs** [comment] 2018-06-05 08:52
Great! From what I've managed to found out, your problem is MacOS specific. If you manage to figure out what the root cause is and how we can fix it, please let me know. For now, I'm going to close this ticket since you have a workaround.

**Closed by josefs** 2018-06-05 08:52 UTC
