### ISSUE TITLE
Implement proper support for polymorphism

### ISSUE THREAD

**Issue by tim2CF** [josefs/Gradualizer#7] opened 2018-06-05 11:40 UTC
Currently I'm investigating ability of using of this tool to analyze Elixir-compiled BEAM bytecode.
BEAM files compiled with Elixir compiler can be decompiled back to Erlang AST/source code.
Example: this file 

https://github.com/coingaming/hm-crypto/blob/17dcf434c75e88506304343aafa9b63106d576a9/lib/hm_crypto/public_key.ex

Can be decompiled back to 

```
-file("/Users/timcf/HTprojects/hm-crypto/lib/hm_cryp"
      "to/public_key.ex",
      1).

-module('Elixir.HmCrypto.PublicKey').

-compile(no_auto_import).

-spec parse_pem(rsa_key()) -> tuple().

-export_type([rsa_key/0]).

-type rsa_key() :: binary() | tuple().

-export(['__info__'/1, parse_pem/1]).

-spec '__info__'(attributes | compile | functions |
                 macros | md5 | module | deprecated) -> any().

'__info__'(module) -> 'Elixir.HmCrypto.PublicKey';
'__info__'(functions) -> [{parse_pem, 1}];
'__info__'(macros) -> [];
'__info__'(attributes) ->
    erlang:get_module_info('Elixir.HmCrypto.PublicKey',
                           attributes);
'__info__'(compile) ->
    erlang:get_module_info('Elixir.HmCrypto.PublicKey',
                           compile);
'__info__'(md5) ->
    erlang:get_module_info('Elixir.HmCrypto.PublicKey',
                           md5);
'__info__'(deprecated) -> [].

parse_pem(Vpem_string@1)
    when erlang:is_binary(Vpem_string@1) andalso
           Vpem_string@1 /= <<>> ->
    [Vpem_entry@1] = public_key:pem_decode(Vpem_string@1),
    public_key:pem_entry_decode(Vpem_entry@1);
parse_pem(Vpem@1) when erlang:is_tuple(Vpem@1) ->
    Vpem@1.
```

When I'm trying to apply Gradualizer to this file, first thing I get is error

```
The atom 'Elixir.HmCrypto.PublicKey' on line 24 does not have type Module
```

I'm not expert in pure Erlang standards, but isn't this atom a valid module name? If I run `erl` shell with loaded BEAM files of application - it works without any issues as module name:

```
Eshell V9.3.1  (abort with ^G)
1> 'Elixir.HmCrypto.PublicKey':parse_pem({hello, world}).
{hello,world}
2>
```
Any ideas about it?

**Comment by gomoripeti** [comment] 2018-06-05 16:21
Hi Tim,

the problem is not Elixir specific. `erlang:get_module_info/1` has the spec defined in `erlang.erl` as:
```
-spec erlang:get_module_info(Module) -> [{Item, term()}] when
      Item :: module | exports | attributes | compile | native | md5,
      Module :: atom().
```

The `Module` type variable is not yet resolved to `atom()` based on the constraints after `when`. This is a feature that will probably be implemented later in Gradualizer.

**Comment by tim2CF** [comment] 2018-06-06 08:01
thanks!

**Comment by josefs** [comment] 2018-06-06 14:12
Peter is exactly right. Type variables are not treated correctly in the current implementation. It's something I'm working on right now, but it's a bit of a thorny issue. I've renamed the issue, and I'll close it once I've implemented the support.

**Comment by tim2CF** [comment] 2018-06-06 14:32
Thank you guys for your work!
I hope I'll also be able to contribute to this project someday :)

**Comment by zuiderkwast** [comment] 2018-12-23 00:36
Is the problem in the example solved by #93?

**Comment by timCF** [comment] 2018-12-23 12:33
Yes, this was fixed, thanks!

**Comment by zuiderkwast** [comment] 2018-12-23 14:19
I'm closing this issue then, although I can't say we have "proper support for polymorphism" yet. It is broad topic. (See e.g. the discussion in #93.)

**Closed by zuiderkwast** 2018-12-23 14:19 UTC
