### ISSUE TITLE
`Report this error to Gradualizer` no function clause matching in :typechecker.handle_type_error/1

### ISSUE THREAD

**Issue by jeremyowensboggs** [josefs/Gradualizer#94] opened 2018-11-19 15:48 UTC
While running gradualizer on an a mature Elixir project, I got quite a few of these:
```
*********************************
Report this error to Gradualizer:

** (FunctionClauseError) no function clause matching in :typechecker.handle_type_error/1

The following arguments were given to :typechecker.handle_type_error/1:

    # 1
    {:type_error, :map, 151, {:type, 141, :union, [{:atom, 0, nil}, {:user_type, 141, :attract_file, []}]}}

    /Users/jowens/dev/snoke/deps/gradualizer/src/typechecker.erl:3327: :typechecker.handle_type_error/1
    /Users/jowens/dev/snoke/deps/gradualizer/src/typechecker.erl:3228: anonymous fn/5 in :typechecker.type_check_forms/2
    (stdlib) lists.erl:1276: :lists.foldr/3
    lib/gradualixir.ex:37: anonymous fn/2 in Gradualixir.gradualize/2
    (elixir) lib/enum.ex:3281: Enumerable.List.reduce/3
    (elixir) lib/enum.ex:1968: Enum.reduce_while/3
    lib/mix/tasks/gradualizer.ex:25: Mix.Tasks.Gradualizer.run/1
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
    (elixir) src/elixir_compiler.erl:71: :elixir_compiler.dispatch/4
    (elixir) src/elixir_compiler.erl:68: :elixir_compiler.compile/3
    (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/2
    (elixir) src/elixir_compiler.erl:23: :elixir_compiler.quoted/2
    (elixir) lib/code.ex:767: Code.require_file/2
    (elixir) lib/kernel/cli.ex:503: Kernel.CLI.wrapper/1
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/kernel/cli.ex:68: Kernel.CLI.process_commands/1
    (elixir) lib/kernel/cli.ex:26: anonymous fn/2 in Kernel.CLI.main/1
    (elixir) lib/kernel/cli.ex:105: anonymous fn/3 in Kernel.CLI.exec_fun/2
```
I was using https://github.com/OvermindDL1/gradualixir

**Comment by OvermindDL1** [comment] 2018-11-19 18:07
Yep, this is just map types not being handled yet, I think it's being fixed in https://github.com/josefs/Gradualizer/pull/59 but probably leave this open to make sure.

**Comment by zuiderkwast** [comment] 2018-11-19 22:08
This is a duplicate of #52. (Re-open if I'm wrong.)

**Closed by zuiderkwast** 2018-11-19 22:08 UTC
